travis:
  secure:
    BINSTAR_TOKEN: Ro8z6F3/9wPiPop+k434qweDd0VTJj7GXyzXGVxEUPwHY2aD0CIObKWnajf9vEleSsdINnauQo6tCYKOI3fXMF6CWP5EfQLxvCXYoi8D7bomkhC0XmnDz4hTse/6fAuodzQXnUjriUEecNL1XA1FSHnMZSyDjfqiFUoyWCGOav+hiInFw0sUXQXYaD93X69hu92mRyaha+dv6v+8vEOWMgNI7NuhENIUYskADq7qKS7kVB3K0gR1eXvEHPLO3oHMcmq8VlIf7jPzt/LA6YkPtPFYI3cAhvaxRDFOg271z0043ymNctehxVhYTZ9dFPPhTgFTJGtzMKvzgNMPw4JO/oeN02km4j+3KczRGVIwtsd+wZNOKu5HwgC1tsZc8aReWHOOZnQRaUXr0jdsWu0oBhkOe5Ivwh5l8c/RW+pa4f9KWgw+/aIG+6pA0v5S6WTj+O0ONrRGNIlx5L9rMD4e90jEKtU40wKXiVrtJABmgdXkNnfeu78v761l4QTc3YKsXfD3a4VYQ+8n4lKj6sRfzTBephqylWWUqOVzIFLbFu6oTHgXtLzWuyuCIHwH6ldNiNjUituD6pI/Q+jK9FMFBU83UOD5716xTkv6zAg932Sdt7BeIPA9JmJlUrpxfL6IzB7oH672bP3+UGRczLLOnV9nUAiwodnFXoagI+xP/qM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {linux_aarch64: default, linux_ppc64le: default}
